version: "3.8"

services:
  localstack:
    container_name: "localstack"
    image: localstack/localstack:latest
    ports:
      - "127.0.0.1:4566:4566" # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559" # external services port range
    environment:
      # - SERVICES=lambda,apigateway,s3 # specifies which AWS services are simulated by LocalStack
      - DEBUG=1 # enables detailed logs for troubleshooting.
      - LAMBDA_EXECUTOR=docker # ensures Lambda functions are executed in Docker containers.
      - LAMBDA_NETWORK=bridge # Sets the Docker network mode for Lambda functions, allowing them to interact with other services on the same network.
      - DOCKER_HOST=unix:///var/run/docker.sock # points LocalStack to the Docker socket on the host machine for interacting with Docker.
    volumes:
      # - "./localstack:/var/lib/localstack" # mounts a directory for persisting LocalStack's state across container restarts.
      - "/var/run/docker.sock:/var/run/docker.sock" # mounts the Docker socket to allow LocalStack to use Docker on the host.
